### ISSUE TITLE
Error with libueye_api 4.82.02-6 : 

### ISSUE THREAD

**Issue by lionep** [FreshXOpenSource/node-ueye#2]
On `camera.init()` call, I have this error : 

```
/home/user/video-capture-ueye/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: /usr/lib/libueye_api.so: undefined symbol: fx_Calibrate
    at DynamicLibrary.get (/home/user/video-capture-ueye/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /home/user/video-capture-ueye/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at new Library (/home/user/video-capture-ueye/node_modules/ffi/lib/library.js:47:28)
    at Object.<anonymous> (/home/user/video-capture-ueye/node_modules/ueye/lib/binding.js:82:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

With which version of libueye api your module work ?

Thanks

**Comment by beno54** [comment]
Hello, 
i've received the same error by doing the same thing than lionep. 

I've corrected this by removing the lines relating to the "fx_Calibrate" in the binding.js.  But is it a good solution ?
